services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: devdiff-db
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: devdiff-app
    ports:
      - "5000:5000"
    environment:
      - PORT=your-port
      - MONGO_URI=your-mongo-uri
    depends_on:
      - mongo

volumes:
  mongo-data:
